### PR TITLE
style: Fixes dropdown navbar in mobile browsers

### PR DESCRIPTION
**Pull request by captn3m0**
- Shifts from pure-css navbar to bootstrap.native
  custom build with only dropdown+collapse support
- Clears some minor unused styles

Tested in the simulator:

image
image

- I really liked https://github.com/thednp/bootstrap.native, which let me drop jQuery very easily compared to the earlier css-only approach I'd tried earlier.

### CODE REVIEW

**Comment by ppaeps** [comment]
Almost!  When I open the "participate" menu, the "join the mailing list" button is half-covered.  Screenshot follows.

hillhacks.in/participate/ on iPhone

**Comment by ppaeps** [comment]
Actually ... never mind.  I just noticed I can scroll.  Feel free to merge this.  Thanks!

**Comment by ppaeps** [comment]
Merged.  Thank you!

**Comment by captn3m0** [comment]
@ppaeps I noticed that as well, but couldn't do anything about it. It has been broken forever. I tried adding a margin-bottom, and experimented a lot with the "correct" way of doing it (`.navbar-btn`) but neither worked out cleanly, so left it as is.

**Pull request merged**
