### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by saloni691**

### CODE REVIEW

**Comment by ppaeps** [comment]
Go away, spammer.

**Comment by mastersilv3r** [comment]
Lets make this a private repo for sometime. Any red flags to this proposal?

**Comment by ppaeps** [comment]
Arguably, it’s a public service to mark these as spam. I don’t mind marking a bunch of these as spam in bulk every couple of days.

**Comment by mastersilv3r** [comment]
👍

**Pull request closed without merging**
