### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Atul-steamcoder**

### CODE REVIEW

**Comment by ppaeps** [comment]
Why is everyone so interested in making minor (questionable) changes to README.md all of a sudden?

**Comment by mastersilv3r** [comment]
Maybe for gaining some brownie points from "Open source contribution" :D

**Comment by shreyas-satish** [comment]
Sorry, this PR isn't addressing any current issue with the website.

**Comment by shreyas-satish** [comment]
Digital Ocean's ["Hacktoberfest"](https://blog.domenic.me/hacktoberfest/) seems like a potential cause.

**Pull request closed without merging**
