### PR TITLE
Adds a code-of-conduct page

### PR DESCRIPTION
**Pull request by Hashfyre**
Adds a conduct page detailing Hillhacks Code of Conduct, adapted from 
https://hasgeek.com/about/policy/code

### CODE REVIEW

**Comment by guneetnarula** [comment]
Thanks!

**Comment by Hashfyre** [comment]
@guneetnarula added the statement you asked for and a version tracker / changelog.

**Comment by shreyas-satish** [comment]
This topic is still under discussion on the mailing list.

In any case, copy pasting a code of conduct from an organization that operates in a different context as compared to hillhacks, doesn't really make sense. It's lazy at best, misleading at worst. Take this for instance:

> Violators, regardless of their standing, may be expelled from the forum, conference venue, and reported to the authorities.

This is in their code of conduct because their structure allows for it to be enforceable. How will this work in the case of hillhacks?

We still don't know how the code of conduct should look like and how it should work at hillhacks. Besides, it's most certainly not just a document we show on the website without thinking through how the space can actually be made safer for everyone.

So, I'm closing this for now.

**Comment by guneetnarula** [comment]
@shreyas-satish I agree with you, copying won't work for us. But I do not think it will be possible for us to draft a CoC without an in-person meeting or a session with a slightly larger set of community members. My suggestion is to keep this for now with a clear objective to draft more relevant and contextual guidelines in May.

**Pull request closed without merging**
