### PR TITLE
Add a link to attic/timeline to the history page

### PR DESCRIPTION
**Pull request by schneider42**

### CODE REVIEW

**Comment by schneider42** [comment]
one moment

**Comment by ppaeps** [comment]
I'd prefer to see content migrated from the attic.

**Comment by captn3m0** [comment]
@schneider42 I prefer having a link instead of the whole timeline here. While the timeline is nice to have on the web, it is not what visitors to the website are looking for.

Your markdown needs slight fixing, though. I'll merge once you fix that :+1:

**Comment by schneider42** [comment]
It would at least be a start, so it can be found. At least there would be an idea where to later put more polished versions of the wiki content.

**Comment by schneider42** [comment]
@captn3m0 can you specify what is from with the markdown?

**Comment by captn3m0** [comment]
It looks like a `[4]` citation in markdown, but shows up as:

timeline[4]

which doesn't look as good. Maybe change that to [timeline][4] instead?

[4]: https://attic.hillhacks.in/timeline

**Comment by schneider42** [comment]
Fixed, at least it looks OK on a local compile

**Comment by captn3m0** [comment]
Thanks a lot :+1:

**Pull request merged**
